export const ACTIONS = {
  RECIEVE_TASKS: "RECIEVE_TASKS",
  ADD_TASK: "ADD_TASK",
  DELETE_TASK: "DELETE_TASK",
  TOGGLE_COMPLETE: "TOGGLE_COMPLETE",
  SET_LOADING: "SET_LOADING",
  SET_MESSAGE: "SET_MESSAGE"
};